-- AlterTable
ALTER TABLE "GameRun" ALTER COLUMN "abandoned" DROP DEFAULT,
ALTER COLUMN "lost" DROP DEFAULT;

-- AlterTable
ALTER TABLE "PlayerRunStats" ADD COLUMN     "goldEarned" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "damageDealt" DROP DEFAULT,
ALTER COLUMN "damageReceived" DROP DEFAULT,
ALTER COLUMN "deaths" DROP DEFAULT,
ALTER COLUMN "upgrade1" DROP DEFAULT,
ALTER COLUMN "upgrade2" DROP DEFAULT,
ALTER COLUMN "upgrade3" DROP DEFAULT;
