export const pages = [
  {
    id: 'home',
    path: '/',
    label: 'Home',
    title: 'Home',
    description: 'Welcome to ft_transcendence',
  },
  {
    id: 'login',
    path: '/login',
    label: 'Login',
    title: 'Login',
    description: 'Login to your account',
  },
  {
    id: 'privacy',
    path: '/privacy',
    label: 'Privacy',
    title: 'Privacy Policy',
    description: 'How this project handles data',
  },
  {
    id: 'terms',
    path: '/terms',
    label: 'Terms',
    title: 'Terms of Service',
    description: 'Rules for using this project',
  },
  {
    id: 'profile',
    path: '/profile',
    label: 'Profile',
    title: 'Profile',
    description: 'View your profile',
  },
  {
    id: 'friends',
    path: '/friends',
    label: 'Friends',
    title: 'Friends',
    description: 'View your friends',
  },
  {
    id: 'lobby',
    path: '/lobby',
    label: 'Lobby',
    title: 'Lobby',
    description: 'Enter the lobby',
  },
  {
    id: 'room',
    path: '/room',
    label: 'Room',
    title: 'Room',
    description: 'Enter a room',
  },
  {
    id: 'game',
    path: '/game',
    label: 'Game',
    title: 'Game',
    description: 'Play a game',
  },
  {
    id: 'leaderboard',
    path: '/leaderboard',
    label: 'Leaderboard',
    title: 'Leaderboard',
    description: 'View the leaderboard',
  },
  {
    id: 'match-history',
    path: '/match-history',
    label: 'Match History',
    title: 'Match History',
    description: 'View your match history',
  },
];
